# Generated by Django 3.0 on 2019-12-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('semester', models.IntegerField()),
                ('address', models.TextField()),
                ('zipcode', models.IntegerField(max_length=200)),
            ],
        ),
    ]
